I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call set_player_name from _set_player_name
  File "game/scripts/set_player_name.rpy", line 6, in script
    $ is_korean = renpy.regex_match("^[가-힣]{2,}$", protagonist_name)
  File "game/scripts/set_player_name.rpy", line 6, in <module>
    $ is_korean = renpy.regex_match("^[가-힣]{2,}$", protagonist_name)
AttributeError: module 'renpy.exports' has no attribute 'regex_match'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call set_player_name from _set_player_name
  File "game/scripts/set_player_name.rpy", line 6, in script
    $ is_korean = renpy.regex_match("^[가-힣]{2,}$", protagonist_name)
  File "/Users/bagbeomjin/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/bagbeomjin/Downloads/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/set_player_name.rpy", line 6, in <module>
    $ is_korean = renpy.regex_match("^[가-힣]{2,}$", protagonist_name)
AttributeError: module 'renpy.exports' has no attribute 'regex_match'

macOS-14.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
do you like band music 1.0
Wed Apr  3 13:58:47 2024
